# setup.sh
# author: arxaqapi
# https://github.com/arxaqapi/Dotfiles

echo "Let's Gong !"
echo "[Warning] - This script will modify the .bashrc file without damaging it (removing content not generated by this script)"

