# setup.sh
# author: arxaqapi
# https://github.com/arxaqapi/Dotfiles

echo "Let's Gong !"
echo "[Warning] - This script will modify the .bashrc file without damaging it (removing content not generated by this script)"

prefix_to_append='# automatially generated: https://github.com/arxaqapi/dotfiles/tree/main/script.sh'
file="$HOME/.bashrc"
exists=0

while read line
do
    if [[ $line == $prefix_to_append ]]
    then
        exists=1
    fi
done < <(cat $file)

# Si le fichier .bashrc contient déjà le sourcage des alias, alors je ne fait rien
if [[ $exists == 1 ]]
then
    echo "[Info] - Les alias ont déjà été généré"
else
    echo -e "\n\n$prefix_to_append" >> $file 
    echo "if [ -f ~/.bash_aliases ]; then" >> $file
    echo "    . ~/.bash_aliases" >> $file 
    echo -e "fi\n" >> $file 
    curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/arxaqapi/Dotfiles/main/.bash_aliases -o $HOME/.bash_aliases
fi
